### ISSUE TITLE
GitCheatFinder (Android App)

### ISSUE THREAD

**Issue by aritra-tech** [Design-and-Code/Quick-projects#10]
I want to add the GitCheatFinder project which is an Android App that helps you to find easily the right Git Commands that you want to use.
Tech used in Kotlin.
Made in Android Studio.
Can you please assign me?

Repository link: https://github.com/aritra-tech/GitCheatFinder

**Comment by Greeshma2903** [comment]
> I want to add the GitCheatFinder project which is an Android App that helps you to find easily the right Git Commands that you want to use. Tech used in Kotlin. Made in Android Studio. Can you please assign me?
> 
> Repository link: https://github.com/aritra-tech/GitCheatFinder

Oh wow, sure, go ahead!
Make sure to get started from the Contributing.md 🚀

**Comment by aritra-tech** [comment]
> > I want to add the GitCheatFinder project which is an Android App that helps you to find easily the right Git Commands that you want to use. Tech used in Kotlin. Made in Android Studio. Can you please assign me?
> > Repository link: https://github.com/aritra-tech/GitCheatFinder
> 
> Oh wow, sure, go ahead! Make sure to get started from the Contributing.md 🚀

Ok, sure I will go through the Contributing.md file
