### ISSUE TITLE
RawTemplate

### ISSUE THREAD

**Issue by binayshaw7777** [Design-and-Code/Quick-projects#19]
I would like to submit a pre-developed android app (Kotlin) consisting of screens like:
1. Splash screen
2. Onboarding Screen
3. SignUp
4. SignIn
5. Forgot Password
6. Homescreen (with Bottom navigation bar)

This will make the development process easy and will also save a lot of time.
@Greeshma2903  please approve. Also, this was a collaborative project where @aritra-tech was involved. Can you please assign him too? We both share equal credit to the app.

**Comment by Greeshma2903** [comment]
Hey, sure you can go ahead! Do read the Contributing.md for the same 🚀

**Comment by aritra-tech** [comment]
> Hey, sure you can go ahead! Do read the Contributing.md for the same 🚀
> 
> @aritra-tech could you comment on this issue? I can then assign this to you as well

Yes @Greeshma2903 please assign me
