### ISSUE TITLE
Django CRUD Application

### ISSUE THREAD

**Issue by TheInspiredConjurer** [Design-and-Code/Quick-projects#8]
I want to create a simple CRUD Application in Django.

Please assign me this issue as part of Hacktoberfest. Thanks!

**Comment by Greeshma2903** [comment]
Hey @TheInspiredConjurer, feel free to add your project as a submodule. You can follow the Contributing.md to contribute 🚀 

🔗 https://github.com/Design-and-Code/Quick-projects/blob/main/CONTRIBUTING.md

**Comment by TheInspiredConjurer** [comment]
Thanks!
